### ISSUE TITLE
Uncaught Errors in console 

### ISSUE THREAD

**Issue by EitanGoldfrad** [webcast/webcast.js#10]
Hey Toots,

I'm running webcaster and I get errors from webcast.js when I try to stop a stream:

> Uncaught TypeError: fn is not a function
> Webcast.Encoder.Mp3.Mp3.close @ webcast.js:210
> Webcast.Encoder.Resample.Resample.close @ webcast.js:325
> self.onmessage @ b8466fdb-c6cc-47c4-8b72-ac8a7cf845f1:22

And then an infinite loop of this error:

> Uncaught Closed
> Shine._encodePass @ libshine.js:14
> Shine.encode @ libshine.js:14
> Webcast.Encoder.Mp3.Mp3.encode @ webcast.js:215
> Webcast.Encoder.Resample.Resample.encode @ webcast.js:349
> self.onmessage @ b8466fdb-c6cc-47c4-8b72-ac8a7cf845f1:16

Any idea what's the cause of it?

Regards

**Comment by toots** [comment]
Hi @EitanGoldfrad,

How are you using the code? The first error seems to indicate a call with the wrong arguments..

**Comment by EitanGoldfrad** [comment]
Hey thanks for replying.
I'm just launching the webcaster code "as-is" and receive the stream in my websocket .
The code seems to work, it just produces an infinite loop of this error.

**Comment by toots** [comment]
Alright, thanks for reporting. There were a couple of bugs/deprecated stuff. Everything should be fixed now!
