### ISSUE TITLE
webcast.js:359 Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by NTShop** [webcast/webcast.js#12]
When trying to use mono mode (1 audio channel setting) from Webcaster then webcast.js throws an error that repeats endlessly until webcaster is told to stop streaming: 

webcast.js:359Uncaught TypeError: Cannot read property 'length' of undefined
Webcast.Encoder.Resample.Resample.concat @ webcast.js:359
Webcast.Encoder.Resample.Resample.encode @ webcast.js:368
self.onmessage @ c36cbe1d-94cf-4466-ba42-5d237f6de5dd:16

To reproduce: Load webcaster, in settings choose mono, click Start Streaming button, monitor JS console to see the errors.

**Comment by toots** [comment]
Fixed, thanks for reporting!
