### ISSUE TITLE
Webcast question

### ISSUE THREAD

**Issue by JipeLie** [webcast/webcast.js#14]
Hey,
You propably going to hate my with this question.
I just start to learn how to use liquidsoap and now i wanted to add you webcast application.

My objectif is to setup the server and access to it from different web client, but I'm totaly lost i don't now where i need to start for setup it, Can you help my ?

Thank you

**Comment by toots** [comment]
Hi,

No worries and thank for your interest! The best way to ask questions is via our mailing list at: savonet-users@lists.sourceforge.net You can subscribe at this address: https://lists.sourceforge.net/lists/listinfo/savonet-users
