### ISSUE TITLE
Add the ablity to restart broken connection.

### ISSUE THREAD

**Issue by smimram** [webcast/webcast.js#26]
With the webcam example (#25), liquidsoap's harbor sometimes stops with
```
2022/08/25 11:07:54 [input.harbor_0:2] Feeding stopped: Ffmpeg_decoder.End_of_file.
```
and in the browser's console we get
```
The connection to ws://localhost:8000/mount was interrupted while the page was loading.
```
Webcast.js should provide a simple way to catch websocket's errors and initiate a new connection.

**Comment by toots** [comment]
The underlying websocket should be present on the webcast's instance:
```javascript
webcast.socket.on("error", ...);
webcast.socket.on("close", ...);
```
Is that enough for you?

**Comment by smimram** [comment]
The thing is that most of the connection stuff is performed by the constructor, which makes it uneasy to reconnect. Let me propose something to you...

**Comment by smimram** [comment]
Actually the main problem is that we cannot catch error performed when constructor's code is executed. I propose #27 to solve this.
